### ISSUE TITLE
[Initial Setup] 프로젝트 환경 및 Git 설정

### ISSUE THREAD

**Issue by nar0ng** [DS-UMC-7th/UMC-7th-TEAM-IOS-FE#1]
# 🛠️ Description for features
프로젝트 초기 설정 작업을 합니다.

## 📝 Todo-lists
- [x] storyboard 파일 삭제
- [x] 프로젝트 Info.plist 수정
- [x] SceneDelegate 설정
- [x] ViewController 작성 후 시뮬레이터 작동 확인
<img width="368" alt="스크린샷 2024-11-28 오후 12 05 31" src="https://github.com/user-attachments/assets/1836597d-4127-40ea-994c-4f81aa61e89a">
